Feature/recon
InTaVia/InTaVia-Backend pull request #62
Opened 2022-11-17 19:51 UTC by jkesanie

2022-11-18 13:11 UTC, sennierer requested changes
could you try to add the the proper model definitions (left some comments in the code), so that we get a valid swagger definition in the API?
Also: is that manifests endpoint needed if we have an proper swagger endpoint delivering a definition of the whole API?
and as a side note: I didnt find any "Franz" (very popular German first name) in the API. Looking at the sparql query it seems to be fine, so probably a problem in the data, do you have an idea where the problem could be?

2022-11-18 13:11 UTC, sennierer commented on main.py
> +    response_model=ReconResponse,
there seems to be something wrong with the response model. at least in my local instance the swagger definitone does not show a proper response shape

2022-11-18 13:11 UTC, sennierer commented on query_parameters.py
> +    type: str
also if adding an enum of allowed values there wouldnt be any need to do manual validation in the view

2022-11-22 08:41 UTC, jkesanie commented
The manifest is part of the reconciliation spec so I think it needs to be there.

2022-11-22 08:44 UTC, sennierer commented
ok, then lets leave the manifest endpoint there

2022-11-22 08:49 UTC, jkesanie commented on query_parameters.py
> +    type: str
The problem is that I don't know how to add stuff to the model in a way that is not visible in the Swagger spec but usable in the template. I want the type parameter to have simple values (Person) which are turned into URI and used in the template. How should this be done? That's the view ifs are currently using URI and and enum for type can't use the original simple values.

2022-11-22 14:21 UTC, merged